apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-wiki-all
  labels:
    type: local
    use: wiki-all
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/wiki"