apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-wiki-site
  labels:
    type: local
    use: wiki-site
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  local:
    path: /wiki/_site
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - esfhblcub01
          - esfhblcub02
          - esfhblcub03