apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-wiki-all
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  selector: 
    matchLabels: 
      type: local
      use: wiki-all