apiVersion: v1
kind: Service
metadata:
  name: wiki-balancer
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  externalIPs:
    - 192.168.1.34
  clusterIP: 10.96.10.10
  selector:
    app: wiki