apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-wiki-site
  labels:
    type: local
    use: wiki-site
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/eshbam01/wiki/_site"