---
- hosts: 192.168.0.44
  remote_user: eshbam01
  become: true
  tasks:
    - name: Configurar netplan en esfhblcub04
      ansible.builtin.copy:
        src: ./Cluster-netplan-config/esfhblcub04.yaml
        dest: /etc/netplan/esfhblcub04.yaml
        owner: eshbam01
        group: eshbam01
        mode: '0644'
    - name: Aplicar cambios netplan
      command: netplan apply
      async: 45
      poll: 0