network:
  version: 2
  renderer: networkd
  ethernets:
    enp0s25:
      addresses:
        - 192.168.1.31/24 # esfhblcub01.lc.pi
        - 192.168.0.45/24 # esfhblcub01.sw.pi
      routes:
        - to: default
          via: 192.168.1.1
          metric: 200
        - to: default
          via: 192.168.0.1
          metric: 300